version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_PORT=3306
      - DB_URL=mysql://sogunshola:password@db4free.net:3306/lendsqrtest
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - busticketBE


networks:
  busticketBE:

volumes:
  data:
    driver: local
